version: '3.8'

services:
  app:
    build: .
    container_name: client-portal-app
    ports:
      - "8001:8001"
    environment:
      APP_ENV: local
      APP_DEBUG: "1"
      APP_URL: "http://localhost:8001"
      DB_CONNECTION: sqlite
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  vite:
    image: node:20-alpine
    container_name: client-portal-vite
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - vite_node_modules:/app/node_modules

  redis:
    image: redis:7-alpine
    container_name: client-portal-redis

volumes:
  vite_node_modules: 